Add ClipBucket
awesome-selfhosted/awesome-selfhosted-data pull request #1016
Opened 2024-12-15 10:24 UTC by tiritibambix

Adding ClipBucket to the list

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-12-17 09:07 UTC, Ki-er requested changes
Some changes.

2024-12-17 09:07 UTC, Ki-er commented on software/clipbucket.yml
> +  - Batchfile
> https://github.com/MacWarrior/clipbucket-v5?tab=readme-ov-file#installation

```suggestion
```

2024-12-17 09:07 UTC, Ki-er commented on software/clipbucket.yml
> +depends_3rdparty: false
Optional so can be removed

```suggestion
```

2024-12-17 09:07 UTC, Ki-er commented on software/clipbucket.yml
> +  - Content Management Systems (CMS)
Video can be under multimedia while CMS is usually for traditional web content management systems.

```suggestion
tags:
  - Media Streaming - Multimedia Streaming
  - Photo and Video Galleries
```

2024-12-17 09:07 UTC, Ki-er commented on software/clipbucket.yml
> +description: "ClipBucket is an Open Source and freely downloadable PHP script that will let you start your own Video Sharing website (YouTube/Netflix Clone) in a matter of minutes."
```suggestion
description: "Start your own Video Sharing website (YouTube/Netflix Clone) in a matter of minutes."
```

2024-12-19 17:38 UTC, tiritibambix commented
I'm sorry I'm pretty much what we call a noob.
Why did the merge fail ? What can I do  ?

2024-12-19 22:14 UTC, Ki-er commented
It failed due to the license `All Rights Reserved` not being present in https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses-nonfree.yml. Id recommend adding it to that list with this PR.

2024-12-20 18:07 UTC, nodiscc requested changes

2024-12-20 18:07 UTC, nodiscc commented on software/clipbucket.yml
> +  - All Rights Reseved
I don't think this is accurate

https://github.com/MacWarrior/clipbucket-v5/blob/master/LICENSE

2024-12-20 18:45 UTC, closed without merging