Added Composio
awesome-selfhosted/awesome-selfhosted-data pull request #1025
Opened 2024-12-18 17:55 UTC by Sheru16

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-12-19 22:21 UTC, Ki-er requested changes

2024-12-19 22:21 UTC, Ki-er commented on software/composio.yml
> +archived: false
Added automatically so can be removed
```suggestion
```

2024-12-28 13:46 UTC, Ki-er requested changes
Another change

2024-12-28 13:46 UTC, Ki-er commented on software/composio.yml
> +description: Integration Platform for AI Agents & LLMs with support for 250+ Apps and custom tools.
Sentence case
```suggestion
description: Integration platform for AI agents & LLMs with support for 250+ apps and custom tools.
```

2024-12-30 05:30 UTC, TheGiraffe3 approved these changes

2025-01-01 12:29 UTC, nodiscc requested changes

2025-01-01 12:29 UTC, nodiscc commented on software/composio.yml
> +  - Unlicense
https://github.com/ComposioHQ/composio/blob/master/LICENSE

```suggestion
  - Elastic-2.0
```

2025-01-04 11:52 UTC, Ki-er approved these changes

2025-01-10 18:54 UTC, merged