Added anki-sync.yml
awesome-selfhosted/awesome-selfhosted-data pull request #1027
Opened 2024-12-20 18:33 UTC by Dacid99

Added the dockerized version of anki-sync server

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-12-24 07:50 UTC, Ki-er requested changes
It would be good too if you could clean up the docs and add a example Docker command people can use.

2024-12-24 07:50 UTC, Ki-er commented on software/anki-sync.yml
> +depends_3rdparty: false
Optional so can be removed
```suggestion
```

2024-12-24 07:50 UTC, Ki-er commented on software/anki-sync.yml
> +  - Docker
```suggestion
platforms:
  - Docker
```

2024-12-28 12:53 UTC, nodiscc commented
Hi @Dacid99 

I will copy-paste here the comment I made on https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/33#issuecomment-2564293893

>  How do we handle software contributions that merely port an existing application to another system (e.g., Dockerization)

>> I don't think we should approve these, it will open the gates to a flood of custom builds, third-party docker images... a quick search returns at least 2 other docker image projects for Anki [[1]](https://github.com/ankitects/anki/pull/2798) [[2]](https://github.com/ankicommunity/ankicommunity-sync-server), so I'd prefer if these solutions could be considered first:
>>- contributing the OCI image build procedure to the upstream project (Dockerfile, documentation)... Anki devs were apparently open to contributions in the issue linked above
>>- linking to the third-party docker image build from the upstream's project documentation

Have you tried to get Docker support added directly into the upstream project (Anki)?

2025-01-05 22:35 UTC, Dacid99 commented
Oh sry i was not aware of this policy, I have not tried to get the official project to endorce this image.
Thanks for the feedback!
Its fine if you close this

2025-01-05 23:28 UTC, closed without merging