add repoflow
awesome-selfhosted/awesome-selfhosted-data pull request #1030
Opened 2024-12-21 12:51 UTC by 100tomer

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [ x] Comments and unused optional fields have been removed.
- [ x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x ] Any software project you are adding to the list is actively maintained.
- [x ] Any software project you are adding was first released more than 4 months ago.
- [x ] Any software project you are adding has working installation instructions.
- [ x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-12-22 11:16 UTC, 100tomer commented
How can I know why the syntax check failed?

2024-12-22 11:27 UTC, nodiscc commented
By clicking on [Details](https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/12445326160/job/34764126124?pr=1030) next to the failed build

```
ERROR:awesome_lint.py: RepoFlow: source_code_url is undefined
ERROR:awesome_lint.py: RepoFlow: licenses Proprietary is not listed in the main licenses list
ERROR:awesome_lint.py: RepoFlow: tags Package Management is not listed in the main tags list
ERROR:awesome_lint.py: RepoFlow: tags Continuous Integration & Deployment is not listed in the main tags list
ERROR:awesome_lint.py: RepoFlow: tags DevOps Tools is not listed in the main tags list
ERROR:awesome_lint.py: RepoFlow: tags Private Repositories is not listed in the main tags list
ERROR:awesome_lint.py: RepoFlow: platforms Node.js is not listed in the main platforms list
ERROR:awesome_lint.py: RepoFlow: platforms PostgreSQL is not listed in the main platforms list
ERROR:awesome_lint.py: RepoFlow: platforms Redis is not listed in the main platforms list
ERROR:awesome_lint.py: RepoFlow: platforms Elasticsearch is not listed in the main platforms list
ERROR:awesome_lint.py: RepoFlow: platforms Helm is not listed in the main platforms list
```

2024-12-22 11:29 UTC, 100tomer commented
> By clicking on [Details](https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/12445326160/job/34764126124?pr=1030) next to the failed build
> 
> ```
> ERROR:awesome_lint.py: RepoFlow: source_code_url is undefined
> ERROR:awesome_lint.py: RepoFlow: licenses Proprietary is not listed in the main licenses list
> ERROR:awesome_lint.py: RepoFlow: tags Package Management is not listed in the main tags list
> ERROR:awesome_lint.py: RepoFlow: tags Continuous Integration & Deployment is not listed in the main tags list
> ERROR:awesome_lint.py: RepoFlow: tags DevOps Tools is not listed in the main tags list
> ERROR:awesome_lint.py: RepoFlow: tags Private Repositories is not listed in the main tags list
> ERROR:awesome_lint.py: RepoFlow: platforms Node.js is not listed in the main platforms list
> ERROR:awesome_lint.py: RepoFlow: platforms PostgreSQL is not listed in the main platforms list
> ERROR:awesome_lint.py: RepoFlow: platforms Redis is not listed in the main platforms list
> ERROR:awesome_lint.py: RepoFlow: platforms Elasticsearch is not listed in the main platforms list
> ERROR:awesome_lint.py: RepoFlow: platforms Helm is not listed in the main platforms list
> ```

thank you, don't know how I missed it. I'll fix it now

2024-12-22 11:47 UTC, 100tomer commented
@nodiscc Sorry to bother you again, what does it mean that a tag must have 3 items attached?
I used 2 tags:
1. Package Management -  I created this tag and added it to this pull request.
2. Software Development - Already exists so I'm not sure why there is a problem.

This is the error I found in the syntax checks:
```
ERROR:awesome_lint.py: 1 items tagged Package Management, each tag must have at least 3 items attached
ERROR:awesome_lint.py: 1 items tagged Software Development, each tag must have at least 3 items attached
```

2024-12-22 13:29 UTC, 100tomer commented
@Rabenherz112 Hi there! I noticed you added the “non-free” tag to this pull request. However, I do offer a free option for self-hosting, which is suitable for personal use. Would you consider this a free option?

2024-12-23 07:15 UTC, nodiscc commented
non-Free = proprietary

https://en.wikipedia.org/wiki/Free_software

2024-12-23 07:16 UTC, nodiscc requested changes

2024-12-23 07:16 UTC, nodiscc commented on software/repoflow.yml
> +  - Software Development
```suggestion
tags:
  - Software Development
```

Please delete `tags/package-management.yml` as well

2024-12-23 07:21 UTC, nodiscc requested changes

2024-12-23 07:21 UTC, nodiscc commented on software/repoflow.yml
> +source_code_url: ""
```suggestion
```

2024-12-23 07:21 UTC, nodiscc commented on software/repoflow.yml
> +  - Proprietary
```suggestion
  - ⊘ Proprietary
```

2024-12-23 10:22 UTC, 100tomer commented
@nodiscc II appreciate your help. Thank you. I’ve just commited all the changes you suggested.

2024-12-23 18:06 UTC, 100tomer commented
@nodiscc The syntax check failed due to 
```
1 items tagged Software Development, each tag must have at least 3 items attached
```
But this tag already exists, what can I do to fix it? 
Thank you

2024-12-24 07:42 UTC, Ki-er requested changes

2024-12-24 07:42 UTC, Ki-er commented on software/repoflow.yml
> +depends_3rdparty: false
Optional so can be removed.
```suggestion
```

2024-12-24 07:42 UTC, Ki-er commented on software/repoflow.yml
> +description: "RepoFlow simplifies package management with support for npm, PyPI, Docker, Go, Helm, and more. Try it for free with 10GB storage, 10GB bandwidth, 100 packages, and unlimited users in th
Cleaner description
```suggestion
description: "Simplify package management for npm, PyPI, Docker, Go, Helm, and more. Try it for free with 10GB storage, 10GB bandwidth, 100 packages, and unlimited users in the cloud, or self-hosted for personal use only."
```

2024-12-24 07:42 UTC, Ki-er commented on software/repoflow.yml
> +  - Software Development
To fix the failed run
```suggestion
  - Software Development - IDE & Tools
```

2024-12-24 07:42 UTC, Ki-er commented on software/repoflow.yml
> +related_software_url: "https://docs.repoflow.io"
Since docs are pretty visible on the main page I dont think we need this
```suggestion
```

2024-12-24 10:42 UTC, 100tomer commented
@Ki-er  Thank you for your suggestions, I’ve commited them.

2024-12-24 16:35 UTC, 100tomer commented
@nodiscc  The syntax check failed with the error “RepoFlow: source_code_url is undefined.” However, in your previous suggestions, you recommended removing it. What should I do in this case? Thank you for your help.

2024-12-25 04:55 UTC, Ki-er commented
Source code is a required field however if no source code exists,t then the website link is substituted - see here: https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/3cx.yml. This is the output - https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#communication---sip

2024-12-25 09:50 UTC, 100tomer commented
> Source code is a required field however if no source code exists,t then the website link is substituted - see here: https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/3cx.yml. This is the output - https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#communication---sip

Thank you for explaining that. However, isn’t it a bit inaccurate to include RepoFlow on the “non-free” list? RepoFlow offers a free version for both cloud and self-hosted environments, which is not a trial or anything similar.

2024-12-26 11:15 UTC, nodiscc commented on software/repoflow.yml
> +description: "Simplify package management for npm, PyPI, Docker, Go, Helm, and more. Try it for free with 10GB storage, 10GB bandwidth, 100 packages, and unlimited users in the cloud, or self-hosted
Yes

2024-12-26 11:16 UTC, nodiscc commented
> inaccurate to include RepoFlow on the “non-free” list? RepoFlow offers a free version

https://en.wikipedia.org/wiki/Free_software

It is non-Free software.

2024-12-27 09:17 UTC, 100tomer commented
> > inaccurate to include RepoFlow on the “non-free” list? RepoFlow offers a free version
> 
> https://en.wikipedia.org/wiki/Free_software
> 
> It is non-Free software.

OK, thank you ! 

And all checks have passed. Can you please approve this pull request?

2024-12-28 10:37 UTC, nodiscc approved these changes

2024-12-29 13:24 UTC, 100tomer commented
Hi @nodiscc, can you please approve it now that all the checks have passed?

2024-12-29 14:46 UTC, Ki-er commented
> Hi @nodiscc, can you please approve it now that all the checks have passed?

This has been approved by nodiscc already, it will be merged in around a week to allow for further feedback from other reviewers

We appreciate your patience.

2025-01-04 11:55 UTC, merged