Add memEx
awesome-selfhosted/awesome-selfhosted-data pull request #1058
Opened 2024-12-31 05:27 UTC by shibaobun

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-12-31 08:14 UTC, Ki-er requested changes
Quick change

2024-12-31 08:14 UTC, Ki-er commented on software/memex.yml
> +  - Elixir
> https://gitea.bubbletea.dev/shibao/memEx#installation

```suggestion
platforms:
  - Docker
```

2025-01-19 14:27 UTC, Ki-er requested changes

2025-01-19 14:27 UTC, Ki-er commented on software/memex.yml
> +description: "A structured, zettlekasten and org-mode inspired memex."
This could be slightly tweaked to explain what a `memex` is in plain English so that people looking for a project but might not know what it is, can be interested.

2025-01-28 21:17 UTC, nodiscc requested changes
@shibaobun the description should explain what the software does, see the other review above.

2025-02-08 11:29 UTC, nodiscc requested changes
minor adjustment

2025-02-13 15:44 UTC, shibaobun commented on software/memex.yml
> +description: "A structured, zettlekasten and org-mode inspired personal knowledge base."
Thank you for the help, this is much more clear! :smile:

2025-03-01 22:16 UTC, nodiscc approved these changes

2025-03-08 09:18 UTC, merged