Add INGInious to Learning and Courses
awesome-selfhosted/awesome-selfhosted-data pull request #115
Opened 2023-09-04 19:43 UTC by nrybowski

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

2023-09-11 23:39 UTC, KieranRobson approved these changes
Looks good to me!

2023-09-12 01:38 UTC, nodiscc requested changes

2023-09-12 01:38 UTC, nodiscc commented on software/inginious.yml
> +description: "INGInious is a secure and automated exercises assessment platform using your own tests, also providing a pluggable interface with your existing LMS."
```suggestion
description: "Intelligent grader that allows secured and automated testing of code made by students."
```

2023-09-12 18:49 UTC, nodiscc approved these changes

2023-09-18 14:32 UTC, merged