Add HoloPlay to Media/Audio Streaming
awesome-selfhosted/awesome-selfhosted-data pull request #121
Opened 2023-09-06 08:18 UTC by stephane-r

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

2023-09-06 09:39 UTC, KieranRobson requested changes
Quick change to be made.

2023-09-06 09:39 UTC, KieranRobson commented on software/holoplay.yml
> +  - React
```suggestion
platforms:
  - Nodejs
  - Docker
```

2023-09-08 11:06 UTC, kokomo123 approved these changes
Since the proper adjustments have been made, I believe this can be approved fully.  It's mature, being actively committed to, etc. Thanks for your contribution

2023-09-18 14:48 UTC, nodiscc commented
>  Any software project you are adding was first released more than 4 months ago.

As far as I can tell the first release was created on July 13, so I don't think this currently qualifies.

2023-09-18 14:49 UTC, kokomo123 commented
I thought it was time of first commit, not first release. Oops.

2023-09-18 14:50 UTC, KieranRobson commented
> I thought it was time of first commit, not first release. Oops.

I use first commit if software does not have a release, I seemed to have also missed this.

2023-09-18 14:50 UTC, closed without merging