Update Cosmos licence
awesome-selfhosted/awesome-selfhosted-data pull request #222
Opened 2023-09-25 20:34 UTC by azukaar

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [ ] Comments and unused optional fields have been removed.
- [ ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [ ] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-09-25 23:15 UTC, nodiscc requested changes

2023-09-25 23:15 UTC, nodiscc commented on software/cosmos.yml
> +  - Apache-2.0
```suggestion
  - Apache-2.0
  - Commons-Clause
```

This is actually correct ^ https://github.com/azukaar/Cosmos-Server/blob/master/LICENCE

2023-09-26 10:10 UTC, azukaar commented
Thanks for the correction!
Also the new suggestion system in Github is super neat
commited now

2023-09-26 13:22 UTC, nodiscc approved these changes

2023-09-26 13:24 UTC, merged