Add DocuSeal to Document Management
awesome-selfhosted/awesome-selfhosted-data pull request #290
Opened 2023-10-17 23:17 UTC by kokomo123

I think docuseal is now mature and I know it's ready for the awesome-selfhosted list as it's past the 4 month mark at this point. Decided to add it myself 👍🏻 As usual, if there's any comments or concerns please let me know and i'll be sure to adjust this PR If necessary. 

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-10-17 23:47 UTC, nodiscc requested changes
> it's past the 4 month mark

Not yet (https://github.com/docusealco/docuseal/releases?page=3), first releases were made in July 2023, so let's wait until 2023/11/10 before we merge this.

Thanks!

2023-10-17 23:47 UTC, nodiscc commented on software/docuseal.yml
> +  - Docker
```suggestion
  - Docker
```

I can't find documentation on how to install from source, Docker seems to be the only supported installation method.

2023-10-17 23:47 UTC, nodiscc commented on software/docuseal.yml
> +depends_3rdparty: no
```suggestion
```

The default value is already `no`, lets remove this

2023-10-17 23:49 UTC, kokomo123 commented
Yeah... i was including july-october. rip

2023-11-10 11:16 UTC, Ki-er commented
Date is 23/11/10 so this is now mature enough!

2023-11-10 12:08 UTC, kokomo123 commented
Woohoo!

2023-11-10 12:54 UTC, nodiscc approved these changes
Thanks

2023-11-10 12:55 UTC, kokomo123 commented
We've certainly sealed the deal on this one (had to wait to make that joke but it was worth it)

2023-11-17 13:14 UTC, merged