Add An Otter Wiki
awesome-selfhosted/awesome-selfhosted-data pull request #336
Opened 2023-11-03 18:12 UTC by SeaswimmerTheFsh

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-11-03 22:09 UTC, KieranRobson requested changes
Some changes to be made.

2023-11-03 22:09 UTC, KieranRobson commented on software/otterwiki.yml
> +description: "Simple, easy to use Wiki software using Markdown."
Sentence case
```suggestion
description: "Simple, easy to use wiki software using markdown."
```

2023-11-03 22:09 UTC, KieranRobson commented on software/otterwiki.yml
> +depends_3rdparty: no
Fixes tags
Depends on 3rd party is optional so this can be removed.
```suggestion
tags:
  - Wikis
```

2023-11-03 22:09 UTC, KieranRobson commented on software/otterwiki.yml
> +name: "An Otter Wiki"
Matches the name of the file and the GitHub repo.
```suggestion
name: "Otter Wiki"
```

2023-11-05 03:28 UTC, SeaswimmerTheFsh commented
I've fixed all of the issues you've pointed out, thanks for the review!

2023-11-07 15:48 UTC, nodiscc requested changes

2023-11-07 15:48 UTC, nodiscc commented on software/otterwiki.yml
> +  - Docker
```suggestion
platforms:
  - Docker
```

The only supported installation method uses Docker (installation in a python virtualenv is only mentioned as a development setup)

2023-11-08 00:39 UTC, kokomo123 commented
After all changes, I will approve this PR as well. 👍🏻

2023-11-08 19:45 UTC, kokomo123 approved these changes
LGTM, thanks!

2023-11-08 21:07 UTC, nodiscc approved these changes

2023-11-13 16:50 UTC, merged

2023-11-20 13:45 UTC, nodiscc commented
This software was already present https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/387