Add Homebox to Inventory Management apps
awesome-selfhosted/awesome-selfhosted-data pull request #351
Opened 2023-11-08 22:58 UTC by Kovah

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

Superseeds #188 which was closed without comments or details, with the original fork being deleted already.

2023-11-09 09:09 UTC, Ki-er requested changes
Tiny tweak to fix sentence case.

2023-11-09 09:09 UTC, Ki-er commented on software/homebox-inventory.yml
> +description: "An inventory and organization system built for the Home User with a focus on simplicity and ease of use."
```suggestion
description: "An inventory and organization system built for the home user with a focus on simplicity and ease of use."
```

2023-11-09 10:53 UTC, Ki-er approved these changes
LGTM- Thanks

2023-11-09 13:30 UTC, nodiscc reviewed
There is another project named `Homebox` (https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/homebox.yml). I think nothing technically prevents 2 projects from having the same `name:`, but shouldn't we rename this one to `Homebox Inventory` just to be safe?

2023-11-09 13:36 UTC, Ki-er commented
Homebox inventory would make sense as when running the actions etc, the distinction there too would be useful.

2023-11-10 12:10 UTC, kokomo123 commented on software/homebox-inventory.yml
> +name: "Homebox"
```suggestion
name: "Homebox Inventory"
```

2023-11-17 13:16 UTC, merged