Add OpenSign™
awesome-selfhosted/awesome-selfhosted-data pull request #406
Opened 2023-11-29 14:18 UTC by nxglabs

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-11-29 14:23 UTC, Ki-er requested changes
Please also remove the comments.

2023-11-29 14:23 UTC, Ki-er commented on software/opensign.yml
> +```yaml
```suggestion
```

2023-11-29 14:23 UTC, Ki-er commented on software/opensign.yml
> +- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
```suggestion
```
```

2024-03-24 18:35 UTC, nxglabs commented
@Ki-er now that the project is more than 4 months old, please add it.

2024-03-24 18:56 UTC, Ki-er requested changes
Some changes to be made.

2024-03-24 18:56 UTC, Ki-er commented on software/opensign.yml
> +name: "OpenSign™"
```suggestion
name: "OpenSign"
```

2024-03-24 18:56 UTC, Ki-er commented on software/opensign.yml
> +  - Docker
See below: Mongodb isnt  platform but does require 3rd party flag.
```suggestion
platforms:
  - Nodejs
  - Docker
```

2024-03-24 18:56 UTC, Ki-er commented on software/opensign.yml
> +  - Free digital signatures
Tags are predefined and can be found here: https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags
Depends on 3rd party due to MongoDB

```suggestion
tags:
  - Document Management
depends_3rdparty: true
```

2024-03-25 10:15 UTC, Ki-er approved these changes
Looks good to me!

2024-03-25 17:09 UTC, nodiscc requested changes

2024-03-25 17:09 UTC, nodiscc commented on software/opensign.yml
> +description: "Free, open source & self-hosted DocuSign alternative."
The description should explain what the software does (you can add `(alternative to DocuSign)` at the end of the description)

2024-03-26 13:49 UTC, Ki-er commented on software/opensign.yml
> +description: "Free, open source & self-hosted document signing software. Alternative to DocuSign."
Syntax for alternatives can be found here:https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#other-guidelines

```suggestion
description: "Free, open source & self-hosted document signing software (alternative to DocuSign)."
```

2024-04-03 17:31 UTC, nodiscc approved these changes

2024-04-13 11:47 UTC, merged