Add WebDB
awesome-selfhosted/awesome-selfhosted-data pull request #423
Opened 2023-12-09 10:34 UTC by aleluff

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-12-09 10:50 UTC, aleluff commented
I just redo entirely the PR

2023-12-09 16:31 UTC, kokomo123 approved these changes
This looks great! Thank you for redoing the PR and making the changes necessary. LGTM.

2023-12-10 05:40 UTC, Ki-er requested changes
Couple changes that could be made.

2023-12-10 05:40 UTC, Ki-er commented on software/webdb.yml
> +demo_url: https://demo.webdb.app/
This is optional so can be removed.
```suggestion
demo_url: https://demo.webdb.app/
```

2023-12-10 05:40 UTC, Ki-er commented on software/webdb.yml
> +  - Self-hosting Solutions
I dont think this fits this tag as its more for all in one solutions.

```suggestion
  - Database Management
  - Software Development - IDE & Tools
```

2023-12-10 05:40 UTC, Ki-er commented on software/webdb.yml
> +description: Open Source and Efficient Database IDE.
Cleaner description that fits sentence case.
```suggestion
description: Efficient database IDE.
```

2023-12-10 10:43 UTC, aleluff commented
Ok for you now ?

2023-12-10 21:15 UTC, Ki-er approved these changes
LGTM - Thanks!

2023-12-11 11:48 UTC, nodiscc approved these changes

2023-12-11 15:35 UTC, aleluff commented
@Ki-er Sorry, I missclick to re-approval buttons

Can I fo something more to make it merge ?

2023-12-11 15:37 UTC, Ki-er commented
>  You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

This will be merged soon. Please be patient.

2023-12-11 15:40 UTC, aleluff commented
Ok my Bad. Thanks

Le lun. 11 déc. 2023, 16:37, Kieran ***@***.***> a écrit :

> You understand that your Pull Request will be merged ~1 week after
> approval, to allow for further comments if needed.
>
> This will be merged soon. Please be patient.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/423#issuecomment-1850325544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZ56R4RB73TNBBCU43N7FTYI4SCVAVCNFSM6AAAAABANWOYOCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJQGMZDKNJUGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-12-20 18:26 UTC, aleluff commented
👋🏻

2023-12-20 20:45 UTC, merged

2023-12-20 20:57 UTC, aleluff commented
🙏