Add Chibisafe
awesome-selfhosted/awesome-selfhosted-data pull request #445
Opened 2023-12-25 16:24 UTC by kzshantonu

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2023-12-27 07:26 UTC, Ki-er requested changes
Couple changes.

2023-12-27 07:26 UTC, Ki-er commented on software/chibisafe.yml
> +  - Docker
JS isnt needed as Nodejs is already present / changed order to match docs
```suggestion
platforms:
  - Docker
  - Nodejs
```

2023-12-27 07:26 UTC, Ki-er commented on software/chibisafe.yml
> +depends_3rdparty: false
Optional so can be removed.
```suggestion
```

2023-12-27 07:28 UTC, Ki-er commented on software/chibisafe.yml
> +description: "Blazing fast file uploader and awesome bunker written in node!"
```suggestion
description: "Blazing fast file uploader and awesome bunker written in node."
```

2024-01-09 23:07 UTC, nodiscc requested changes
Better description

2024-01-09 23:07 UTC, nodiscc commented on software/chibisafe.yml
> +description: "Blazing fast file uploader and awesome bunker written in node."
```suggestion
description: "File uploader service that aims to to be easy to use and set up. It accepts files, photos, documents, anything you imagine and gives you back a shareable link for you to send to others."
```

2024-01-13 11:15 UTC, Rabenherz112 approved these changes

2024-01-13 13:19 UTC, nodiscc approved these changes

2024-01-20 13:16 UTC, merged