Add CASE
awesome-selfhosted/awesome-selfhosted-data pull request #462
Opened 2024-01-04 10:10 UTC by SebConejo

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-01-04 10:58 UTC, nodiscc commented
Hi,
We only list end user applications, not frameowrks/libraries/SDKs.

2024-01-04 11:22 UTC, SebConejo commented
Hi @nodiscc .

I understood that. Bu I think there is a misunderstood regarding CASE. This is a backend like appwrite or Pocketbase. If these tools are legitimately listed, CASE should be too.

2024-01-04 11:24 UTC, nodiscc commented
Thanks for the heads-up @SebConejo, I will take another look at Appwrite and Pocketbase to determine if they should actually be listed.

2024-01-24 19:38 UTC, ryangurn requested changes
Can you please fix the platforms and ensure that the tags are correctly formatted?

2024-01-24 19:38 UTC, ryangurn commented on software/case.yml
> +platforms:
These do not appear to be valid platforms.

2024-01-24 19:38 UTC, ryangurn commented on software/case.yml
> +  - Software Development - Low Code - Backend
The formatting here does not look correct.

2024-01-25 17:24 UTC, nodiscc commented
@ryangurn Don't mind the errors, I'm just keeping this PR open to remind me to 

> take another look at Appwrite and Pocketbase to determine if they should actually be listed.

(see comments). But I should probably open an issue instead.

2024-01-27 11:31 UTC, nodiscc approved these changes
Since this procudes a basic working application without writing any code, I've changed my mind and decided it could be included. The unwritten guideline about SDKs/libraries not being in scope for the list needs to be refined and written down.

```bash
nvm use 18
npx create-case-app my-case-app
-> working backend/admin panel at http://localhost:4000/auth/login
```

2024-01-27 11:31 UTC, nodiscc commented on software/case.yml
> +  - Javascript
```suggestion
  - Nodejs
```

2024-01-27 11:31 UTC, nodiscc commented on software/case.yml
> +description: Instant backend in TS with DB, Admin panel, API, JS SDK
```suggestion
description: Lightweight BaaS (Backend As A Service) requiring minimal coding, with database, admin panel, API, and Javascript SDK.
```

2024-02-09 22:13 UTC, merged