Add tine
awesome-selfhosted/awesome-selfhosted-data pull request #469
Opened 2024-01-05 07:48 UTC by mzch

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-01-13 11:13 UTC, Rabenherz112 requested changes

2024-01-13 11:13 UTC, Rabenherz112 commented on software/tine.yml
> +description: tine is the ideal software for digital collaboration in companies and organizations. From powerful groupware functionalities to clever add-ons, tine combines everything to make daily tea
```suggestion
description: Software for digital collaboration in companies and organizations. From powerful groupware functionalities to clever add-ons, tine combines everything to make daily team collaboration easier.
```

2024-01-13 11:13 UTC, Rabenherz112 commented on software/tine.yml
> +  - PHP
```suggestion
  - Docker
```
[Installation Guide](https://tine-docu.s3web.rz1.metaways.net/operators/Installation_Guide/) only mentions Docker

2024-01-20 13:22 UTC, mzch reviewed
plz commit sugested change.

2024-01-20 13:22 UTC, mzch commented on software/tine.yml
> +description: tine is the ideal software for digital collaboration in companies and organizations. From powerful groupware functionalities to clever add-ons, tine combines everything to make daily tea
Ok.

2024-01-20 13:22 UTC, mzch commented on software/tine.yml
> +  - PHP
Thanks.

2024-01-20 13:47 UTC, nodiscc approved these changes

2024-01-24 19:36 UTC, ryangurn approved these changes

2024-01-27 11:34 UTC, merged