Added Keploy
awesome-selfhosted/awesome-selfhosted-data pull request #490
Opened 2024-01-11 20:36 UTC by Arindam200

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [ ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [ ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-01-13 10:45 UTC, Rabenherz112 commented on software/keploy.yml
> +  - Docker
```suggestion
platforms:
  - Docker
  - Go
```

2024-01-13 10:49 UTC, Rabenherz112 commented on software/keploy.yml
> +demo_url: "https://www.youtube.com/watch?v=23yQaY81Zho"
```suggestion

```

2024-01-13 10:53 UTC, Rabenherz112 commented on software/keploy.yml
> +  - API Management
```suggestion
tags:
  - Software Development - Testing
```

2024-01-13 10:54 UTC, Rabenherz112 commented on software/keploy.yml
> +depends_3rdparty: false
```suggestion
```

2024-01-13 11:02 UTC, Rabenherz112 requested changes

2024-01-13 13:28 UTC, nodiscc reviewed
This seems to be a purely command-line application - we don't list those. Or am I missing something, such as a self-hosted web interface that allows you to view test results?

2024-01-16 21:46 UTC, Arindam200 commented
> This seems to be a purely command-line application - we don't list those. Or am I missing something, such as a self-hosted web interface that allows you to view test results?

It has a self-hosted interface for the enterprise users.

2024-01-18 19:26 UTC, nodiscc commented
> It has a self-hosted interface for the enterprise users.

Where can I find the source code for this self-hosted enterprise edition, and what is the license?

2024-01-24 16:39 UTC, ryangurn approved these changes
The YML looks as expected and the URLs do exist as expected.

2024-02-22 17:54 UTC, nodiscc commented
> It has a self-hosted interface for the enterprise users.
>> Where can I find the source code for this self-hosted enterprise edition, and what is the license?

No reply for > a month, closing

2024-02-22 17:54 UTC, closed without merging