Add ryot
awesome-selfhosted/awesome-selfhosted-data pull request #615
Opened 2024-03-12 06:35 UTC by AlexTu2

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-03-12 09:17 UTC, Ki-er requested changes
Couple suggested changes.

2024-03-12 09:17 UTC, Ki-er commented on software/ryot.yml
> +demo_url: "ryot.fly.dev"
```suggestion
demo_url: "https://ryot.fly.dev/auth/login?redirectTo=%2F"
```

2024-03-12 09:17 UTC, Ki-er commented on software/ryot.yml
> +depends_3rdparty: false
```suggestion
```

2024-03-12 09:17 UTC, Ki-er commented on software/ryot.yml
> +  - Rust
> https://github.com/ignisda/ryo

```suggestion
platforms:
  - Docker
```

2024-03-12 09:27 UTC, AlexTu2 commented
> Couple suggested changes.

Changes have been made

2024-03-21 18:27 UTC, nodiscc requested changes

2024-03-21 18:27 UTC, nodiscc commented on software/ryot.yml
> +  - Time Tracking
```suggestion
tags:
  - Personal Dashboards
```


More fitting category

2024-03-21 18:27 UTC, nodiscc commented on software/ryot.yml
> +description: "Platform for tracking various facets of your life - media, fitness etc."
```suggestion
description: "Platform for tracking various facets of your life - media, fitness, etc."
```

Minor syntax fix

2024-03-21 19:37 UTC, AlexTu2 commented
@nodiscc changes have been made

2024-03-21 19:39 UTC, nodiscc approved these changes

2024-04-03 17:31 UTC, merged