Adding EverShop to the E-commerce software list
awesome-selfhosted/awesome-selfhosted-data pull request #657
Opened 2024-04-10 03:17 UTC by treoden

Adding EverShop to the E-commerce software list

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-04-12 10:16 UTC, kokomo123 commented on software/evershop.yml
> +demo_url: https://demo.evershop.io/
```suggestion
demo_url: https://demo.evershop.io/
depends_3rdparty: true
```
I propose adding this flag as due to paypal, stripe is out of the user's control.

2024-04-13 10:12 UTC, Rabenherz112 requested changes

2024-04-13 10:12 UTC, Rabenherz112 commented on software/evershop.yml
> +  - Nodejs
```suggestion
platforms:
  - Docker
  - Nodejs
```

Also [supports Docker](https://evershop.io/docs/development/getting-started/installation-guide#install-evershop-using-docker) as an installation method

2024-04-13 10:51 UTC, treoden commented on software/evershop.yml
> +  - Nodejs
Thanks. Updated

2024-04-13 13:46 UTC, Rabenherz112 approved these changes

2024-04-14 15:06 UTC, nodiscc requested changes

2024-04-14 15:06 UTC, nodiscc commented on software/evershop.yml
> +description: EverShop is a NodeJS ecommerce platform with essential commerce features. Built with NodeJS and React. Modular architecture and fully customizable.
```suggestion
description: E-commerce platform with essential commerce features. Modular architecture and fully customizable.
```

shorter description

2024-04-22 15:10 UTC, treoden commented
Hi,

Thank you for your reviews , are we waiting for some thing else?

Thanks

2024-04-22 15:31 UTC, Ki-er commented
>  You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

We appreciate your patience, however this will be merged whenever Nodiscc is available!

2024-04-22 17:24 UTC, merged