Add Pinepods
awesome-selfhosted/awesome-selfhosted-data pull request #673
Opened 2024-04-23 14:12 UTC by madeofpendletonwool

Added in Pinepods Podcast Management Platform

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-04-24 04:45 UTC, ryangurn reviewed
LGTM!

2024-04-24 07:37 UTC, Rabenherz112 requested changes
On a side note, how do I use the demo? I've set up an account called "Dummy," but I'm struggling to test anything within it, all I seem to see are empty pages?

2024-04-24 07:37 UTC, Rabenherz112 commented on software/pinepods.yml
> +description: "PinePods is a Rust based podcast management system that manages podcasts with multi-user support and relies on a central database with clients to connect to it. It's browser based and y
> description of what the software does, shorter than 250 characters, sentence case

A possible alternative description below, but feel free to change it however you want to make it get it under 250 characters.

```suggestion
description: "A podcast management system with multi-user support which relies on a central database with clients to connect to it."
```

2024-04-24 07:37 UTC, Rabenherz112 commented on software/pinepods.yml
> +depends_3rdparty: false
This can be omitted, as the default case is false.

```suggestion
```

2024-04-24 07:37 UTC, Rabenherz112 commented on software/pinepods.yml
> +related_software_url: "https://my.awesome.softwar.e/apps"
```suggestion
```

2024-04-24 15:24 UTC, madeofpendletonwool commented
> On a side note, how do I use the demo? I've set up an account called "Dummy," but I'm struggling to test anything within it, all I seem to see are empty pages?

You probably need to search for and add some podcasts. Nothing will show up on the pages other than messages instructing you to add podcasts until you've added a feed of your own. You can search for podcasts with the search bar at the top right.

2024-04-24 15:29 UTC, madeofpendletonwool commented
Changes have been made as requested. Thanks for the review!

2024-04-26 06:53 UTC, Rabenherz112 approved these changes

2024-04-26 10:43 UTC, nodiscc approved these changes

2024-04-26 17:31 UTC, ryangurn approved these changes
LGTM!

2024-05-02 20:33 UTC, merged