Master
awesome-selfhosted/awesome-selfhosted-data pull request #692
Opened 2024-05-05 09:02 UTC by filipecarneiro

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-05-07 13:30 UTC, kokomo123 commented on software/e-label.yml
> +depends_3rdparty: false
```suggestion
```
No need for this line as it's already default to false.

2024-05-12 08:14 UTC, Rabenherz112 requested changes

2024-05-12 08:14 UTC, Rabenherz112 commented on software/e-label.yml
> +description: "Open-source solution for electronic labels, with QR Codes, on wine bottles sold within the European Union. This initiative seeks to enhance transparency, efficiency, and information acc
The description should only describe what the software does. Additionally terms such as open-source should be avoided ([see here](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#other-guidelines))
Possible alternative description; however, feel free to re-write it yourself according to your preferences!
```suggestion
description: "Solution for electronic labels, with QR code support on wine bottles sold within the European Union."
```

2024-05-12 08:14 UTC, Rabenherz112 commented on software/e-label.yml
> +  - K8S
The deployment sections only mention docker as a way to install this software.
```suggestion
  - Docker
```

2024-05-12 08:14 UTC, Rabenherz112 commented on software/e-label.yml
> +  - URL Shorteners
Miscellaneous and URL Shorteners don't seem to fit here.
If your software does a built-in Inventory Management tool, I am fine with this tag, but I couldn't find anything on the GitHub project mentioning it.
```suggestion
  - Community-Supported Agriculture (CSA)
```

2024-05-12 08:14 UTC, Rabenherz112 commented on software/e-label.yml
> +demo_url: "https://qr.doutorpc.net/l/GR904-2015"
> Demo links should only be used for interactive demos

I wouldn't count this static website as interactive, but maybe other reviews want to share their opinion on that.
```suggestion
```

2024-06-05 20:19 UTC, nodiscc commented
@filipecarneiro please address the points mentioned in the review

2024-06-15 07:22 UTC, nodiscc commented
@filipecarneiro ping

2024-06-22 15:41 UTC, kokomo123 approved these changes
Looking clean and concise now, think we can merge this, thanks nodiscc 💯

2024-07-09 16:28 UTC, nodiscc approved these changes

2024-07-17 17:45 UTC, merged