Add dropserver
awesome-selfhosted/awesome-selfhosted-data pull request #722
Opened 2024-05-29 18:03 UTC by teleclimber

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-07-11 19:25 UTC, teleclimber commented
Hi, I wrote that over 2 years and have been improving things a lot since then (I do need to rework the site). Also, "general use" relates to being usable by non-technical people, because that's the ultimate goal of this project (though it's a long way off). People with home labs or whatever, the kind of people who browse awesome-self-hosted would be able to make good use of it in its current state.

But in any case, it's up to you. Thanks.

2024-09-29 09:57 UTC, nodiscc commented
"not yet ready for general use" was dropped from the website. Let's re-evaluate this

2024-12-28 13:41 UTC, Ki-er requested changes
Couple changes

2024-12-28 13:41 UTC, Ki-er commented on software/dropserver.yml
> +description: "An Application Platform for Your Personal Web Services."
Sentence case
```suggestion
description: "An application platform for your personal web services."
```

2024-12-28 13:41 UTC, Ki-er commented on software/dropserver.yml
> +depends_3rdparty: false
Default false so can be removed
```suggestion
```

2025-01-19 13:44 UTC, Ki-er commented
@teleclimber Please see the above changes.

2025-01-31 14:06 UTC, nodiscc commented
@teleclimber ping

2025-02-04 22:22 UTC, Ki-er approved these changes

2025-02-04 22:23 UTC, Ki-er approved these changes

2025-02-05 18:03 UTC, nodiscc approved these changes

2025-02-12 19:17 UTC, merged