Add Wavelog
awesome-selfhosted/awesome-selfhosted-data pull request #729
Opened 2024-06-01 15:12 UTC by HB9HIL

Reopend this PR as mentioned in #693. Thanks for review

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

Related to #690 and #693

2024-06-05 20:23 UTC, nodiscc requested changes

2024-06-05 20:23 UTC, nodiscc commented on software/wavelog.yml
> +related_software_url: "https://github.com/wavelog"
This is usually used to provide a link to mobile/desktop clients or related application. I don't think it is very useful to point to the organizatino page, other projects listed there are not likely to be used by end users.

2024-06-08 08:50 UTC, Rabenherz112 approved these changes

2024-06-08 12:14 UTC, kokomo123 approved these changes
No issues here

2024-06-15 07:24 UTC, nodiscc approved these changes

2024-06-22 15:34 UTC, merged