Add Puter
awesome-selfhosted/awesome-selfhosted-data pull request #784
Opened 2024-07-16 01:46 UTC by jelveh

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-07-18 01:43 UTC, kokomo123 approved these changes
LGTM, No issues here pending other thoughts from contributors. Thanks for your contribution!

2024-07-21 20:54 UTC, kokomo123 commented on software/puter.yml
> +  - File Transfer - Distributed Filesystems
```suggestion
```
This tag refers to another list, think the other two will be fine 👍🏻

2024-07-27 17:20 UTC, nodiscc requested changes

2024-07-27 17:20 UTC, nodiscc commented on software/puter.yml
> +description: A privacy-first personal cloud to keep all your files, apps, and games in one secure place, accessible from anywhere at any time.
```suggestion
description: Web-based operating system designed to be feature-rich, exceptionally fast, and highly extensible
```

Better description

2024-08-01 17:43 UTC, Rabenherz112 approved these changes

2024-08-01 20:49 UTC, nodiscc approved these changes

2024-08-01 21:01 UTC, nodiscc requested changes

2024-08-01 21:01 UTC, nodiscc commented on software/puter.yml
> +description: Web-based operating system designed to be feature-rich, exceptionally fast, and highly extensible
```suggestion
description: Web-based operating system designed to be feature-rich, exceptionally fast, and highly extensible.
```

2024-08-01 21:01 UTC, nodiscc approved these changes

2024-08-09 16:37 UTC, merged