Add software “solidtime”
awesome-selfhosted/awesome-selfhosted-data pull request #808
Opened 2024-08-05 15:27 UTC by korridor

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-08-05 16:54 UTC, Rabenherz112 commented
Hi, thanks for your contribution.

Currently, this project has a release, but it is not yet 4 months old. Our guidelines require that _Any software project you are adding was first released more than 4 months ago_. This count initiates only after a release has been created to ensure users need not rely on the latest development version to use the project.

I'll go ahead and close it for now to keep the PR section focused on active tasks. Once the first release is four months old, feel free to resubmit it to awesome-selfhosted, or you can create an issue instead (we don't close issues; we just tag them to indicate they need to mature).

Thanks for understanding, and good luck with this project.

2024-10-30 17:04 UTC, korridor commented
@Rabenherz112 
Thanks for the feedback! I wanted to inform you that the first release of solidtime is now older than 4 months.
Would be great if you could look at the PR again. I'll also create an issue and link this PR.

2024-10-30 17:21 UTC, Ki-er requested changes
> https://docs.solidtime.io/self-hosting/intro

I would improve the docs a little too. Include a sample docker command to install for example, add some detail etc

2024-10-30 17:21 UTC, Ki-er commented on software/solidtime.yml
> +  - PHP
>https://docs.solidtime.io/self-hosting/intro

PHP can be removed

```suggestion
```

2024-10-30 17:49 UTC, korridor commented
@Ki-er I'll remove "PHP" from the platforms, but I don't really understand your comment regarding the docs.

Do you mean the docs should include more information or do you mean I should link the docs somehow?

2024-10-30 17:51 UTC, Ki-er commented
> Do you mean the docs should include more information or do you mean I should link the docs somehow?

Docs should include more information, such as how to use docker to install it, i.e a sample command to get it up and running

2024-10-30 17:52 UTC, korridor commented
@Ki-er The link you sent is only the introduction there are many more pages (see navigation on the left) and a whole GitHub repository with self-hosting examples.
Link to the docker self-hosting guide: https://docs.solidtime.io/self-hosting/guides/docker
Link to the self-hosting examples repository (also linked in the docs): https://github.com/solidtime-io/self-hosting-examples

2024-11-01 13:41 UTC, korridor commented on software/solidtime.yml
> +  - PHP
Just removed that in the PR.

2024-11-01 18:00 UTC, korridor commented
@Ki-er I just updated the docs page to link more clearly to docker self-hosting guide: https://docs.solidtime.io/self-hosting/intro

2024-11-05 19:12 UTC, nodiscc requested changes

2024-11-05 19:12 UTC, nodiscc commented on software/solidtime.yml
> +description: "solidtime is a modern time tracking application for freelancers and agencies."
```suggestion
description: "Modern time tracking application for freelancers and agencies."
```

https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#other-guidelines

2024-11-12 20:48 UTC, nodiscc approved these changes

2024-11-18 17:42 UTC, merged