add Prisme Analytics
awesome-selfhosted/awesome-selfhosted-data pull request #810
Opened 2024-08-08 11:42 UTC by negrel

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-08-15 21:13 UTC, kokomo123 approved these changes
LGTM, no issues here. Pending other thoughts from collaborators, thank you for your contribution!!! 💯

2024-08-19 08:01 UTC, Rabenherz112 requested changes

2024-08-19 10:27 UTC, negrel commented on software/prisme-analytics.yml
> +description: "An Open Source, privacy-focused and progressive analytics service."
done

2024-08-19 10:27 UTC, negrel commented on software/prisme-analytics.yml
> +  - Docker
done

2024-08-19 10:27 UTC, negrel commented on software/prisme-analytics.yml
> +depends_3rdparty: false
done

2024-08-19 17:48 UTC, nodiscc requested changes

2024-08-19 17:48 UTC, nodiscc commented on software/prisme-analytics.yml
> +  - Monitoring
```suggestion
```

```
ERROR:awesome_lint.py: 1 items tagged Monitoring, each tag must have at least 3 items attached
ERROR:awesome_lint.py: Prisme Analytics: tag Monitoring points to a tag which redirects to another list.
```

Monitoring tools are listed at https://github.com/awesome-foss/awesome-sysadmin?tab=readme-ov-file#monitoring. Analytics is enough.

2024-08-19 20:06 UTC, nodiscc approved these changes

2024-08-20 06:08 UTC, Rabenherz112 approved these changes

2024-08-25 14:49 UTC, merged