Add bewCloud
awesome-selfhosted/awesome-selfhosted-data pull request #850
Opened 2024-09-05 13:46 UTC by BrunoBernardino

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-09-05 15:13 UTC, Ki-er requested changes

2024-09-05 15:13 UTC, Ki-er commented on software/bewcloud.yml
> +depends_3rdparty: false
```suggestion

```

2024-09-05 15:13 UTC, Ki-er commented on software/bewcloud.yml
> +  - Javascript
With  Nodejs being present this isnt needed.
```suggestion
```

2024-09-06 13:02 UTC, kokomo123 approved these changes
LGTM, shouldn't be anything wrong. Pending further thoughts from collaborators. Thank you for your contribution!

2024-09-29 09:36 UTC, nodiscc requested changes

2024-09-29 09:36 UTC, nodiscc commented on software/bewcloud.yml
> +  - Knowledge Management Tools
```suggestion
```

does not apply, if this refers to the notes functionality, this is covered by `Note-taking & Editors`

2024-10-12 14:22 UTC, nodiscc requested changes

2024-10-12 14:22 UTC, nodiscc commented on software/bewcloud.yml
> +  - Docker
```suggestion
platforms:
  - Docker
```

Docker is the only supported deployment method

>  Values for platform are the main server-side requirements for the software. Don't include frameworks or specific dialects.

2024-10-19 13:15 UTC, nodiscc approved these changes

2024-10-27 10:13 UTC, merged