To add software beaver habtit tracker
awesome-selfhosted/awesome-selfhosted-data pull request #881
Opened 2024-10-02 14:26 UTC by daya0576

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-11 07:44 UTC, Ki-er requested changes
Couple changes to be made.

2024-10-11 07:44 UTC, Ki-er commented on software/beaverhabits.yml
> +  - Docker
> https://github.com/daya0576/beaverhabits?tab=readme-ov-file#self-hosting

```suggestion
platforms:
  - Docker
```

2024-10-11 07:44 UTC, Ki-er commented on software/beaverhabits.yml
> +  - Miscellaneous
By having a category, it is inherently not misc so this can be removed. 

```suggestion
tags:
  - Time Tracking
```

2024-10-11 15:00 UTC, daya0576 commented
@Ki-er Thanks a lot for your comments, I have updated my code and am now waiting for the next workflow to verify.

2024-10-22 16:21 UTC, Ki-er requested changes
Another quick change

2024-10-22 16:21 UTC, Ki-er commented on software/beaverhabits.yml
> +description: "A self-hosted habit tracking app to save your precious moments in your fleeting life."
```suggestion
description: "Habit tracking app to save your precious moments in your fleeting life."
```

2024-10-24 15:33 UTC, daya0576 commented
Thank you, that makes sense as all the software is self-hosted.

2024-10-27 10:14 UTC, nodiscc approved these changes

2024-11-11 21:19 UTC, merged