Add GlobaLeaks Whistleblowing Software
awesome-selfhosted/awesome-selfhosted-data pull request #883
Opened 2024-10-07 16:00 UTC by evilaliv3

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-11 07:42 UTC, Ki-er requested changes
Quick change to be made

2024-10-11 07:42 UTC, Ki-er commented on software/globaleaks.yml
> +description: "GlobaLeaks is free, open-source whistleblowing software enabling anyone to easily set up and maintain a secure reporting platform. "
```suggestion
description: "A whistleblowing software enabling anyone to easily set up and maintain a secure reporting platform. "
```

2024-10-19 20:39 UTC, evilaliv3 commented
Thank you for the feedback @Ki-er !

It is good to go from my side.

2024-10-19 22:36 UTC, nodiscc requested changes

2024-10-19 22:36 UTC, nodiscc commented on software/globaleaks.yml
> +description: "A whistleblowing software enabling anyone to easily set up and maintain a secure reporting platform. "
```suggestion
description: "Whistleblowing software enabling anyone to easily set up and maintain a secure reporting platform. "
```

https://english.stackexchange.com/questions/12990/why-dont-we-use-the-indefinite-article-with-software

2024-10-19 22:36 UTC, nodiscc commented on software/globaleaks.yml
> +name: "GlobaLeaks Whistleblowing Software"
```suggestion
name: "GlobaLeaks"
```

2024-10-20 07:06 UTC, evilaliv3 commented
Thank you for your feedback @nodiscc

2024-10-20 08:34 UTC, nodiscc approved these changes

2024-10-27 10:13 UTC, merged