Add OpnForm
awesome-selfhosted/awesome-selfhosted-data pull request #894
Opened 2024-10-14 12:18 UTC by JhumanJ

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-14 15:56 UTC, nodiscc requested changes

2024-10-14 15:56 UTC, nodiscc commented on software/opnform.yml
> +depends_3rdparty: false
```suggestion
```

This is already the default value, can be removed

2024-10-14 15:56 UTC, nodiscc commented on software/opnform.yml
> +archived: false
```suggestion
```

These fields are kept up-to-date automatically, no need to include them.

2024-10-14 15:56 UTC, nodiscc commented on software/opnform.yml
> +description: "Beautiful open-source form builder"
```suggestion
description: "Beautiful open-source form builder."
```

2024-10-14 16:05 UTC, JhumanJ commented
@nodiscc thanks for the fast review - all applied.

2024-10-22 16:28 UTC, Ki-er requested changes
Very very pedantic review, lets remove the empty whitespace.

2024-10-22 16:28 UTC, Ki-er commented on software/opnform.yml
> +
```suggestion
```

2024-10-22 17:13 UTC, JhumanJ commented
> Very very pedantic review, lets remove the empty whitespace.

Done!

2024-10-27 10:13 UTC, merged