CASE is now Manifest
awesome-selfhosted/awesome-selfhosted-data pull request #901
Opened 2024-10-22 08:42 UTC by brunobuddy

Replaces the old CASE software by Manifest as the project name and vision changed.

2024-10-22 13:36 UTC, kokomo123 approved these changes
It looks fine to me, pending other thoughts from collaborators. Thank you for your contribution!

2024-10-23 16:17 UTC, nodiscc requested changes
```
ERROR:awesome_lint.py: Manifest: source_code_url is undefined
```

2024-10-23 16:28 UTC, kokomo123 commented
I did not catch that, oops!

2024-10-23 16:51 UTC, Ki-er requested changes
Apparently this review didnt publish so here it is

2024-10-31 21:48 UTC, nodiscc commented on software/manifest.yml
> +  - Software Development - Low Code
@brunobuddy ping

2024-11-12 08:07 UTC, brunobuddy commented on software/manifest.yml
> +  - Software Development - Low Code
@nodiscc @Ki-er thank you, I commited the suggestion. However somhehow I still have a conflict on the `case.yml` file that I deleted.

2024-11-12 13:02 UTC, nodiscc commented on software/manifest.yml
> +  - source_code_url: https://github.com/mnfst/manifest
```suggestion
source_code_url: https://github.com/mnfst/manifest
```

2024-11-12 13:02 UTC, nodiscc approved these changes

2024-11-12 14:43 UTC, kokomo123 approved these changes
LGTM, no problems here.

2024-11-15 17:22 UTC, closed without merging

2024-11-15 17:34 UTC, nodiscc commented
Merged in https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/a8587a7fde789ee42859e1eb67132886e09f60c4
I mistakenly pushed another repo's git history to @brunobuddy's fork. https://github.com/brunobuddy/awesome-selfhosted-data/ is now a mirror of Shaarli's source code :ok_hand: . I suggest you delete your fork.