add selfhostblocks
awesome-selfhosted/awesome-selfhosted-data pull request #910
Opened 2024-10-24 09:47 UTC by ibizaman

I am adding [SelfHostBlocks](https://github.com/ibizaman/selfhostblocks) to the repository. It is a project I maintain since 2 years now and that I use daily for myself and keep improving.

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-24 10:32 UTC, Ki-er requested changes
Quick change

2024-10-24 10:32 UTC, Ki-er commented on software/selfhostblocks.yml
> +description: " Modular server management based on NixOS modules and focused on best practices. "
```suggestion
description: "Modular server management based on NixOS modules and focused on best practices."
```

2024-10-24 13:45 UTC, kokomo123 approved these changes
This looks to be in proper order, LGTM

2024-12-28 13:41 UTC, Ki-er requested changes

2024-12-28 13:41 UTC, Ki-er commented on software/selfhostblocks.yml
> +  - Automation
This doesn't seem to be appropriate for this project
```suggestion
```

2024-12-28 17:10 UTC, TheGiraffe3 approved these changes

2024-12-28 19:21 UTC, Ki-er approved these changes

2025-01-04 11:45 UTC, nodiscc approved these changes

2025-01-10 18:55 UTC, nodiscc requested changes
`ERROR:awesome_lint.py: selfhostblocks.yml: file should be named self-host-blocks.yml`

2025-02-06 09:51 UTC, Ki-er commented
No response in 4 weeks, closing for now.

2025-02-06 09:51 UTC, closed without merging