add Mybucks.online
awesome-selfhosted/awesome-selfhosted-data pull request #911
Opened 2024-10-24 16:05 UTC by koko37

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [ ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [ ] Comments and unused optional fields have been removed.
- [ ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.
- [ ] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-25 10:35 UTC, kokomo123 commented
Please check boxes with [X]

2024-10-25 15:36 UTC, Ki-er requested changes
React isnt a platform

2024-10-25 15:36 UTC, Ki-er commented on software/mybucks.online.yml
> +  - React
```suggestion
```

2024-10-28 01:58 UTC, koko37 commented
Please review again.
@Ki-er

2024-10-28 10:50 UTC, kokomo123 approved these changes
LGTM, no issues here pending other thoughts from collaborators. Thank you for your contribution!

2024-12-28 13:43 UTC, Ki-er reviewed
I cant seem to access https://app.mybucks.online/, is this offline or is it a client issue?

2024-12-28 14:32 UTC, TheGiraffe3 commented
That URL opens for me, though it requires a password/new account.

2025-01-03 01:11 UTC, koko37 commented
Cool. you can try any credentials, and that will create a crypto wallet for you.
app.mybucks.online is a password-only crypto wallet.
@TheGiraffe3 @Ki-er

2025-01-03 01:14 UTC, koko37 commented
Try this test credentials please:
password: **DemoAccount5&**
passcode: **112324**

2025-01-03 03:57 UTC, TheGiraffe3 approved these changes
Yep, that works for me. Looks very nice.

2025-01-04 11:43 UTC, nodiscc approved these changes

2025-01-10 18:53 UTC, merged