Add Cannery
awesome-selfhosted/awesome-selfhosted-data pull request #917
Opened 2024-10-26 15:33 UTC by shibaobun

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-10-26 15:41 UTC, kokomo123 commented
Hi there, feel free to resubmit as this doesn't seem right, feel free to use the templates listed here: https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md

2024-10-26 15:58 UTC, shibaobun commented
@kokomo123 this is a bit of a weird request, but could you reopen this PR for a moment? Thank you!

2024-10-26 16:11 UTC, kokomo123 commented
@shibaobun unfortunately, this can't be reopened since u already made a new one. Apologies

2024-10-26 16:18 UTC, shibaobun commented
@kokomo123 this is a special case, and I want to close it immediately afterwards, would that be okay?

2024-10-26 16:22 UTC, kokomo123 commented
I really can't do that either way, I want to but github is refusing to reopen the PR.

2024-10-26 16:22 UTC, kokomo123 commented
Testing.

2024-10-26 16:22 UTC, kokomo123 commented
![image](https://github.com/user-attachments/assets/ae329c38-c675-46a1-9c43-8b73d27b9aee)

2024-10-26 16:23 UTC, shibaobun commented
Ah, thank you for trying then

2024-10-26 16:28 UTC, shibaobun commented
@kokomo123 Actually sorry, I'd really like to fix this issue. Is this PR able to be reopened now?

2024-10-26 16:35 UTC, kokomo123 commented
Thanks @nodiscc :)

2024-10-26 16:35 UTC, shibaobun commented
Sorry about that, seems like it didn't work :pensive:
This PR should be ready to merge now though! If anyone is curious, they can email me at shibao@bubbletea.dev for more details

2024-10-26 16:47 UTC, shibaobun commented
I think I've fixed the issues by the previous linter run. I just assumed that the tags were user-created, but now I've referenced it with Inventory Management, which makes more sense. I swear my PRs are usually not this messy :sweat_smile:

2024-10-27 10:17 UTC, kokomo123 approved these changes
LGTM, no issues here, pending further thoughts from collaborators. Thank you for your contribution!

2024-11-02 11:42 UTC, Rabenherz112 requested changes

2024-11-02 11:42 UTC, Rabenherz112 commented on software/cannery.yml
> +description: "A self-hosted firearm and ammunition tracker app."
Small change to remove redundancy
```suggestion
description: "Firearm and ammunition tracker app."
```

2024-11-02 19:10 UTC, Rabenherz112 approved these changes

2024-11-05 18:36 UTC, nodiscc approved these changes

2024-11-11 21:20 UTC, merged