Add xx network Haven
awesome-selfhosted/awesome-selfhosted-data pull request #938
Opened 2024-11-05 07:21 UTC by armchairancap

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-11-05 18:35 UTC, kokomo123 commented on software/xx-network-haven.yml
> +depends_3rdparty: false
```suggestion
```
No need for this line as it's already set to false. Thanks 👍🏻

2024-12-12 14:42 UTC, Ki-er requested changes
Couple of changes

2024-12-12 14:42 UTC, Ki-er commented on software/xx-network-haven.yml
> +description: "anonymous, distributed, mixnet-based text messaging chat app. Uses xx network's cMixx technology by Dr. David Chaum. Not to be confused with Haven the blogging system."
Sentence case

```suggestion
description: "Anonymous, distributed, mixnet-based text messaging chat app. Uses xx network's cMixx technology by Dr. David Chaum. Not to be confused with Haven the blogging system."
```

2024-12-12 14:42 UTC, Ki-er commented on software/xx-network-haven.yml
> +  - Docker
> https://git.xx.network/elixxir/speakeasy-web/

Docker not present so can be removed,

```suggestion
```

2024-12-28 13:44 UTC, Ki-er approved these changes

2025-01-04 12:25 UTC, kokomo123 approved these changes
LGTM, thanks for your contribution!

2025-01-20 17:09 UTC, armchairancap commented
Can another person review this, or can this be merged, perhaps?

If anyone thinks something still has to be improved, please let me know.

2025-01-20 18:42 UTC, nodiscc commented on software/xx-network-haven.yml
> +description: "Anonymous, distributed, mixnet-based text messaging chat app. Uses xx network's cMixx technology by Dr. David Chaum. Not to be confused with Haven the blogging system."
I do not understand what this does or how it works. The description should state this as plainly as possible.

> https://xx.network
>The First High-Speed Quantum Resistant Decentralized Mixnet with Blockchain.
>Protect metadata for dApps, chains, and businesses with advanced quantum-resistant security.
>Precomputation with cMixx delivers real-time calculations hundreds of times faster than other mixnets.

Yeah, this does not help...

> https://git.xx.network/elixxir/speakeasy-web#getting-started
> run the development server:

Are there installation instructions for production use?

2025-01-28 21:22 UTC, nodiscc requested changes
See review above

2025-01-30 08:53 UTC, armchairancap commented
> See review above

Makes sense.
If I add "What is Haven" to the intro page - https://armchairancap.github.io/docs/intro - and update the doco link to point to that URL (from there people can pick User Guide or Admin Guide), would that be better?

2025-03-18 20:37 UTC, Ki-er commented
No response in a couple months, lets close this for now.

2025-03-18 20:37 UTC, closed without merging