add clipcascade
awesome-selfhosted/awesome-selfhosted-data pull request #945
Opened 2024-11-10 00:03 UTC by Sathvik-Rao

Development began in July, with beta testing completed in August, and the first release launched in September. Now, it's in a major, stable version. It stands out as a unique solution in the self-hosted clipboard category, with no similar project listed on [Awesome Selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted). People need to see and use this—it’s ready and shouldn't be marked as needing more time to mature.

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-11-11 21:16 UTC, nodiscc commented
>  Any software project you are adding was first released more than 4 months ago.

First release came out on September, 23 https://github.com/Sathvik-Rao/ClipCascade/releases

Please resubmit (or remind us to reopen this PR) after January 4, 2025.

Thanks

2025-02-02 08:47 UTC, Sathvik-Rao commented
Hi @nodiscc 

I wanted to follow up on the request to reopen the PR, as per your previous message.

Thanks

2025-02-02 12:46 UTC, Ki-er commented on software/clipcascade.yml
> +  - Miscellaneous # need a tag for ClipBoard
The comment isnt needed here however it is a good idea if there are other clipboard manager projects in Misc or other categories.

```suggestion
  - Miscellaneous
```

2025-02-02 12:46 UTC, Ki-er requested changes
Quick change

2025-02-06 09:28 UTC, Sathvik-Rao commented
Hi @Ki-er 

Anything else needed from my side?

2025-02-08 11:40 UTC, nodiscc requested changes

2025-02-08 11:40 UTC, nodiscc commented on software/clipcascade.yml
> +  - Docker
```suggestion
platforms:
  - Java
  - Docker
```

2025-03-01 22:17 UTC, nodiscc approved these changes

2025-03-08 09:18 UTC, merged

2025-04-30 02:54 UTC, Birdie2024-boop approved these changes