add What to Cook?
awesome-selfhosted/awesome-selfhosted-data pull request #959
Opened 2024-11-15 17:32 UTC by kassner

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-11-16 01:10 UTC, Ki-er requested changes
Quick change

2024-11-16 01:10 UTC, Ki-er commented on software/whattocook.yaml
> +archived: false
```suggestion
```

2024-11-19 11:59 UTC, kokomo123 commented on software/whattocook.yaml
> +  - Java
```suggestion
```
Seeing as the only installation method is Docker, this isn't needed.

2024-11-19 18:28 UTC, kokomo123 approved these changes
LGTM, no issues here pending other thoughts from collaborators. Thanks for your contribution!

2024-12-08 11:56 UTC, nodiscc requested changes

2024-12-08 11:56 UTC, nodiscc commented on software/whattocook.yaml
> +description: Click a button and get a recipe. You can exclude unavailable ingredients, but you can't just get another recipe.
```suggestion
description: Get a recipe to cook today, based on the ingredients you have at home.
```

2024-12-16 22:48 UTC, nodiscc approved these changes

2024-12-22 11:37 UTC, merged