add not-th.re
awesome-selfhosted/awesome-selfhosted-data pull request #977
Opened 2024-11-23 12:23 UTC by scolastico

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-11-25 11:16 UTC, Rabenherz112 approved these changes

2024-11-25 12:31 UTC, kokomo123 approved these changes
LGTM, pending other thoughts from collaborators. Thank you for your contribution!

2024-11-27 12:23 UTC, nodiscc requested changes

2024-11-27 12:23 UTC, nodiscc commented on licenses.yml
> +
This is a Non-Free license, it must be moved to https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses-nonfree.yml

2024-12-08 11:54 UTC, nodiscc requested changes

2024-12-08 11:54 UTC, nodiscc commented on software/not-three.yml
> +description: "Simple, secure by client side encryption, featuring the monaco editor known from vs-code, paste sharing platform."
```suggestion
description: "Simple paste sharing platform, with client side encryption, featuring the monaco browser-based code editor."
```

2024-12-16 22:51 UTC, nodiscc approved these changes

2024-12-22 11:38 UTC, merged