Add HomeServerHQ
awesome-selfhosted/awesome-selfhosted-data pull request #978
Opened 2024-11-24 15:55 UTC by homeserverhq

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

2024-11-25 13:11 UTC, kokomo123 approved these changes
LGTM, pending other thoughts from collaborators. Thank you for your contribution!

2024-12-12 14:44 UTC, Ki-er requested changes
Quick change

2024-12-12 14:44 UTC, Ki-er commented on software/homeserverhq.yaml
> +description: "HomeServerHQ is an all-in-one home server infrastructure and installer that embarrasses its competition. Have a fully configured email server, VPN, and public website(s) set up in less
A less boastful and more descriptive description.
```suggestion
description: "All-in-one home server infrastructure. It is designed to be simple and easy for anyone to setup and use, even without any prior software/IT experience."
```

2024-12-12 15:25 UTC, homeserverhq commented
@Ki-er - I made some modifications as per your request. Is it suitable now?

2024-12-28 13:44 UTC, Ki-er approved these changes

2025-01-04 11:47 UTC, nodiscc approved these changes

2025-01-04 11:52 UTC, Ki-er approved these changes

2025-01-05 21:49 UTC, dejongr6 commented on software/homeserverhq.yaml
> +  - Self-hosting Solutions
```

2025-01-05 22:00 UTC, dejongr6 commented
- Ready set up job

2025-01-05 22:03 UTC, dejongr6 commented on software/homeserverhq.yaml
> +  - Self-hosting Solutions
Set up job

2025-01-19 13:25 UTC, merged